# cấu hình pytest
[pytest]

# nơi pytest sẽ tìm test
testpaths = tests

# option mặc định khi chạy pytest
addopts = -v --tb=short --html=reports/report.html --self-contained-html

# khai báo custom markers
markers =
    smoke: smoke test
    sanity: sanity test
    regression: regression test
    login: login related test
    ui: ui test

